/**
 * @author Ankush Chavan
 * @description Here we have declare all action type
 */

export const ADD_STUDENT_STARTED = "ADD_STUDENT_STARTED";
export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS";
export const ADD_STUDENT_FAIL = "ADD_STUDENT_FAIL";

export const VIEW_STUDENT_STARTED = "VIEW_STUDENT_STARTED";
export const VIEW_STUDENT_SUCCESS = "VIEW_STUDENT_SUCCESS";
export const VIEW_STUDENT_FAIL = "VIEW_STUDENT_FAIL";

export const EDIT_STUDENT_STARTED = "EDIT_STUDENT_STARTED";
export const EDIT_STUDENT_SUCCESS = "EDIT_STUDENT_SUCCESS";
export const EDIT_STUDENT_FAIL = "EDIT_STUDENT_FAIL";

export const DELETE_STUDENT_STARTED = "DELETE_STUDENT_STARTED";
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS";
export const DELETE_STUDENT_FAIL = "DELETE_STUDENT_FAIL";
